name: ci

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v2

      - name: T
        run: echo "SEC ${{ secrets.MY_SECRET }}"

