name: Test Outputs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: foo
        run: |
          const fs = require("fs");
          const os = require("os");
          fs.appendFileSync(
            process.env["GITHUB_OUTPUT"],
            `foo=bar${os.EOL}`
          );
        shell: node '{0}'
      - name: Print output
        run: |
          echo "FOO: ${{ steps.foo.outputs.foo }}"