name: Test Outputs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: foo
        run: ./script.js
      - name: Print output
        run: |
          echo "FOO: ${{ steps.foo.outputs.foo }}"